from tkinter import *
window=Tk()
window.title("Login app")
window.geometry('300x300')
frame=Frame(window,bg="maroon",height=200,width=200)
frame.pack()
l1=Label(frame,text="enter your name")
l1.pack()
e1=Entry(frame)
e1.pack()
l2=Label(frame,text="enter your password")
l2.pack()
e2=Entry(frame)
e2.pack()
def fun():
    name=e1.get()
    txt.insert(END,"welcome "+name)
b1=Button(frame,text="click me",command=fun)
b1.pack ()
txt=Text(frame)
txt.pack()
window.mainloop()